name: Trying out github actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  
jobs:
  simple_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
    steps:
      - name: Print github context
        run: echo $GGITHUB_CONTEXT
