name: Trying out github actions

on:
  pull_request:
    types: [ opened, reopened, closed ]
  
jobs:
  simple_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
    steps:
      - name: Print github context
        run: echo $GGITHUB_CONTEXT
