name: Trying out github actions

on:
  pull_request:
    types: [ opened, reopened, closed ]
  
jobs:
  simple_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo 'Hello'
