name: Slack notifications testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  simple_job:
    runs-on: ubuntu-latest
    steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: ${{ github.actor }}
        custom_payload: | 
          {
            attachments: [{
             text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB}` 
            }]
          }
        #text: ${{ format( 'A new version {0} is deployed to {1} by {2} and the build took {3}' , github.sha, 'some concatenated text', github.job ) }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: success() # Pick up events even if the job fails or is canceled.
