name: Slack notifications testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  simple_job:
    runs-on: ubuntu-latest
    steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: ${{ github.actor }}
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
            }]
          }
        #text: ${{ format( 'A new version {0} is deployed to {1} by {2} and the build took {3}' , github.sha, 'some concatenated text', github.job ) }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: success() # Pick up events even if the job fails or is canceled.
