name: Slack notifications testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  simple_job:
    runs-on: ubuntu-latest
    steps:
    - name: Some failing job
      run: some-failing-job # will return command not found
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Integration Test # default: 8398a7@action-slack
        fields: repo,commit,message,author # default: repo,commit
        mention: here
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
