name: Slack notifications testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  simple_job:
    runs-on: ubuntu-latest
    steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: ${{ github.actor }}
        text: ${{ format( {github.actor} , 'some concatenated text', {github.job} ) }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: success() # Pick up events even if the job fails or is canceled.
