name: Trying out github actions

on:
  push:
    branches:
      - main
  
jobs:
  simple_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
    steps:
      - name: Print github context
        run: echo $GITHUB_CONTEXT
      - name: Print all env variables
        run: printenv
      - name: This should run only when ref branch is print-jobs and event is push
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/print-jobs' }}
        run: echo 'Event is push and ref is print-jobs'
      - name: This should run only when ref branch is print-jobs and event is pull request
        if: ${{ github.event_name == 'pull_request' && github.ref == 'refs/heads/print-jobs' }}
        run: echo 'Event is pull request and ref is print-jobs'
