name: Trying out github actions

on:
  push:
    branches:
      - print-jobs
  
jobs:
  simple_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
    steps:
      - name: Print github context
        run: echo $GITHUB_CONTEXT
      - name: Print all env variables
        run: printenv
