name: Trying out github actions

on:
  push:
    branches:
      - main
  
jobs:
  simple_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
      COMMIT_MESSAGE: ${{ toJSON(github.event.commits.*.message) }}
    steps:
      - name: Print commit message
        run: echo $COMMIT_MESSAGE

